<h1 class="page-title"> Dodavanje novog albuma
    <div class="btn-group pull-right">
        <a href="<?php echo $this->resourceUrl()->index('index');?>"  class="btn sbold green">
            <i class="fa fa-arrow-left"></i>&nbsp;
            Nazad
        </a>
    </div>
</h1>

<div class="row">
    <div class="col-md-12">
        <div class="portlet light">
            <div class="portlet-body">
                <div class="row">

                    <?php echo $this->form; ?>

                    <div class="col-md-12">
                        <div id="uploader" style="display: none;">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php
    $this->htmlLibraries()->library('fileinput');
    $this->htmlLibraries()->library('jqueryui');
    $this->htmlLibraries()->library('plupload');
?>

<script>
    <?php $this->inlineScript()->captureStart(); ?>

    $('.submit').on('click', function (e) {
       e.preventDefault();
       e.stopPropagation();

       var formData = $('.form').serializeArray();

        $.ajax({
            url: '<?php echo $this->url(['controller' => 'admin_multimedia', 'action' => 'create']) ;?>',
            method: 'post',
            data:  {
                formData: formData
            },
        }).done(function(data) {
            console.log(data);
            $('#uploader').fadeIn();
        }).fail(function() {
            console.log('There was error while communicated with server.');
        });

    });

    $(function() {
        $("#uploader").pluploadQueue({
            runtimes : 'html5,flash,silverlight,html4',
            url : "<?php echo $this->url(['controller' => 'admin_multimedia', 'action' => 'upload'], 'default', true);?>",
            rename : true,
            dragdrop: true,
            max_file_count: 20,
            prevent_duplicates: true,
            multiple_queues: true,
            sortable: true,
            views: {
                list: true,
                thumbs: true,
                active: 'thumbs'
            },
            filters : {
                max_file_size : '5mb',
                mime_types: [
                    {title : "Image files", extensions : "jpg,gif,png"},
                ]
            },
        });
    });

    <?php $this->inlineScript()->captureEnd(); ?>
</script>
