<?php

class Admin_EditorController extends \ForceX\Controller\Action
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {

    }

}