<?php

class Admin_PartnerController extends \ForceX\Controller\Action
{
    public function init()
    {
        $this->_helper->viewRenderer->setNoRender(TRUE);
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {

    }

    public function createAction()
    {

    }
}